runtime: nodejs18
env: standard
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 2
env_variables:
  NODE_ENV: production
  # Any other environment variables can go here
